## Model Tuning using RandomSearchCV

In [177]:
# importing libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [178]:
df = sns.load_dataset('iris')

In [179]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [180]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [181]:
from sklearn.model_selection import train_test_split

X = df.drop('species',axis = 1)
y = df['species']

In [182]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

### for SVC

In [188]:
from sklearn.svm import SVC
model_svm = SVC(C = 10, kernel='linear', gamma= 'auto')
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [189]:
model_svm.score(X_test,y_test)

1.0

In [192]:
from sklearn.model_selection import RandomizedSearchCV
     
classifier = RandomizedSearchCV((model_svm),{ # we put the multiples hyperparameters in svm model
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter=4 ,cv = 5,return_train_score = False)
     
classifier.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [196]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002317,0.000767,0.001477,0.000330,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
1,0.002036,0.000744,0.001240,0.000274,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
2,0.001183,0.000040,0.001011,0.000161,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001318,0.000205,0.000982,0.000138,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2

In [197]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1       30          rbf         0.960000
2       10          rbf         0.980000
3       20          rbf         0.966667

### Hence during the hyperparameter tuning (using RandomizedsearchCV) in SVM model the best accuracy comes from putting the parameters to C=10,kernal=rbf.